
jobs:
  job.one:
    job: SimpleJob
    description: My Job is simple 
    cron: '*/1 * * * * ?'
    config:
      color: blue
      an_array:
        - one
        - two
  job.two:
    job: StatelessJob
    cron: '*/1 * * * * ?'
  job.three:
    job: SimpleJob
    cron: '*/1 * * * * ?'
    config:
      color: blue
      an_array:
        - one
        - two
      raise_error: true
  job.four:
    job: StatelessJob
    cron: '*/1 * * * * ?'
    stopped: true

queues:
  /queue/response:
    durable: false
  /queue/init_params:
    durable: false
  /queue/stateless_response:
    durable: false
  /queue/error:
    durable: false
