source 'http://rubygems.org'

gem 'rails', '3.1.0.rc4'
gem 'sprockets', '= 2.0.0.beta.13'


# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'


gem 'jruby-openssl'
gem 'torquebox'


# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

