source "file://#{File.dirname(__FILE__)}/../../../../build/assembly/target/stage/gem-repo"
gem "sinatra"
gem "torquebox"
gem "data_mapper", "1.1.0"
gem "dm-sqlite-adapter", "1.1.0"
gem 'jdbc-sqlite3'
