
require 'net/http'
require 'uri'

task :default

def install_dependency(url, group_id, artifact_id, version, type )
  puts "Installing #{url} as #{group_id}:#{artifact_id}:#{version}:#{type}"

  fetch_path = File.join( BUILD_DIR, "#{artifact_id}.#{type}" )

  puts "fetch_path=#{fetch_path}"

  file fetch_path do
    puts "fetching #{url} to #{fetch_path}"
    fetch_to( url, fetch_path )
  end

  group_segments = group_id.split( '.' )
  path_segments = [ LOCAL_REPO_DIR, group_segments, artifact_id, version ].flatten

  artifact_dir = File.join( path_segments )
  artifact_path = File.join( artifact_dir, "#{artifact_id}-#{version}.#{type}" )


  file artifact_path do
    FileUtils.mkdir_p( artifact_dir )
    puts "installing #{artifact_path}"
    Rake::Task[fetch_path].invoke()
    FileUtils.cp( fetch_path, artifact_path )
  end
  
  task :default=>artifact_path

end

def fetch_to(url_path, destination)
  puts "Fetching #{url_path}"
  url = URI.parse(url_path)
  FileUtils.mkdir_p( File.dirname( destination ) )
  Net::HTTP.start(url.host, url.port) do |http|
    File.open( destination, 'w' ) do |f|
      http.get( url.path ) do |segment|
        f.write( segment )
      end
      puts "Completed"
    end
  end
end


=begin
JRUBY_TARGET_FILE=File.join( BUILD_DIR, File.basename( JRUBY_ARTIFACT_ZIP ) )
JBOSS_TARGET_FILE=File.join( BUILD_DIR, File.basename( JBOSS_ARTIFACT_ZIP ) )

task :default=>[ JRUBY_ARTIFACT_ZIP, JBOSS_ARTIFACT_ZIP ]

file JRUBY_ARTIFACT_ZIP do 
  Rake::Task[JRUBY_TARGET_FILE].invoke()
  puts "Installing #{JRUBY_ARTIFACT_ZIP}"
  FileUtils.mkdir_p( File.dirname( JRUBY_ARTIFACT_ZIP ) )
  FileUtils.cp( JRUBY_TARGET_FILE, JRUBY_ARTIFACT_ZIP )
end

file JRUBY_TARGET_FILE do
  fetch( JRUBY_BIN_URL )
end

file JBOSS_ARTIFACT_ZIP do
  Rake::Task[JBOSS_TARGET_FILE].invoke()
  puts "Installing #{JBOSS_ARTIFACT_ZIP}"
  #FileUtils.mkdir_p( File.dirname( JBOSS_ARTIFACT_ZIP ) )
  #FileUtils.cp( JBOSS_TARGET_FILE, JBOSS_ARTIFACT_ZIP )
end

file JBOSS_TARGET_FILE do
  fetch( JBOSS_BIN_URL )
end


=end
