source 'http://rubygems.org'

gem 'rails', '~>3.1.0'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'activerecord-jdbc-adapter'
gem 'jdbc-sqlite3'

gem 'jruby-openssl'
gem 'json'

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

gem "torquebox-rake-support"
gem "torquebox"
