
version = ENV['project.version'] || ENV['VERSION'] || '1.0.0'

if ( version =~ /^([0-9]+)\.([0-9]+)\.([0-9]+)(\..*)?/ )
  PROJECT_VERSION="#{$1}.#{$2}.#{$3}"
end

task :default=>[:package]


task :package=>[ :package_container, :package_client ]

task :stage do 
  Dir.chdir( "target/gem-stage" ) do 
    FileUtils.cp( "../torquebox-messaging.jar", "java-lib/torquebox-messaging-#{version}.jar" )
    FileUtils.rm_f( 'lib' )
    FileUtils.ln_s( '../../src/main/ruby/lib',     'lib' )
  end
end

task :package_container=>:stage do 
  Dir.chdir( "target/gem-stage" ) do 
    gem_spec = eval( File.read( "../../torquebox-messaging-container.gemspec" ) )
    Gem::Builder.new( gem_spec ).build
    FileUtils.mv( "torquebox-messaging-container-#{PROJECT_VERSION}.gem", "../torquebox-messaging-container-#{PROJECT_VERSION}.gem" )
  end
end

task :package_client=>:stage do 
  Dir.chdir( "target/gem-stage" ) do 
    gem_spec = eval( File.read( "../../torquebox-messaging-client.gemspec" ) )
    Gem::Builder.new( gem_spec ).build
    FileUtils.mv( "torquebox-messaging-client-#{PROJECT_VERSION}.gem", "../torquebox-messaging-client-#{PROJECT_VERSION}.gem" )
  end
end

