source "file://#{File.dirname(__FILE__)}/../../../../build/assembly/target/stage/gem-repo"

# Project requirements
#gem 'sinatra-flash', :require => 'sinatra/flash'

# Component requirements
gem 'sass'
gem 'haml'

# Padrino Stable Gem
gem 'padrino', '0.10.5'

