require "#{File.dirname(__FILE__)}/../etc/tasks/torquebox"
TorqueBox::RakeHelper.install_standard_tasks
TorqueBox::RakeHelper.install_java_tasks(:gemspec => 'torquebox-core.gemspec',
                                         :copy_deps => 'lib/wunderboss-jars',
                                         :excluded_deps => ['jruby-complete'])

task :default => :spec
