source :rubygems

gem 'rake'
gem 'sinatra-flash', :require => 'sinatra/flash'

# Component requirements
gem 'bcrypt-ruby', :require => "bcrypt"
gem 'haml'
gem 'activerecord', :require => "active_record"

gem 'activerecord-jdbc-adapter'
gem 'jdbc-sqlite3'

# Padrino Stable Gem
gem 'padrino'

# Or Padrino Edge
# gem 'padrino', :git => 'git://github.com/padrino/padrino-framework.git'
