source "file://#{File.dirname(__FILE__)}/../../../../assemblage/assembly/target/stage/gem-repo"
source 'http://rubygems.org'

gem 'haml'

gem 'rails', '~>3.0.0'
gem 'activerecord-jdbc-adapter'
gem 'jdbc-sqlite3'
