require 'rake/gempackagetask'

version = ENV['project.version'] || ENV['VERSION'] || '1.0.0'

if ( version =~ /^([0-9]+)\.([0-9]+)\.([0-9]+)(\..*)?/ )
  PROJECT_VERSION="#{$1}.#{$2}.#{$3}"
end

task 'maven:package'=>[ :package ]

spec = eval( File.read( "src/main/assembly/torquebox-gem.gemspec" ) )

Rake::GemPackageTask.new(spec) do |pkg|
    pkg.package_dir = 'target/gems'
end
