
require 'open3'
require 'rake/gempackagetask'


TEST_DATA_IN  = File.dirname(__FILE__) + '/test-data'
TEST_DATA_OUT = File.dirname(__FILE__) + '/target/test-data'

DEP_JARS_DIR = File.dirname(__FILE__) + '/target/dependencies'

RUBYSPEC_DIR = File.dirname(__FILE__) + '/rubyspec'
BIN_DIR      = File.dirname(__FILE__) + '/bin'

SPECS = [
  'core/dir',
  'core/file',
  #'core/io',
]

desc "Prepare test-data"
task 'test:data:prepare' do
  puts "preparing test-data"

  FileUtils.rm_rf( TEST_DATA_OUT )
  FileUtils.mkdir_p( TEST_DATA_OUT )

  paths = Dir[ TEST_DATA_IN + '/**/*' ]
  paths.sort!{|l,r| r.length <=> l.length}
  #paths = paths.collect{|e| e[ TEST_DATA_IN.length..-1] }

  paths.each do |path|
    subpath = path[ TEST_DATA_IN.length..-1 ]
    if ( File.directory?( path ) )
      if ( path =~ /\.jar$/ )
        puts "replace dir with real jar for #{subpath}"
        Dir.chdir( "#{TEST_DATA_OUT}/#{subpath}" ) do 
          cmd = "jar cvf #{TEST_DATA_OUT}/#{subpath}.tmp ."
          puts cmd
          `#{cmd}`
        end
        FileUtils.rm_rf "#{TEST_DATA_OUT}/#{subpath}"
        FileUtils.mv "#{TEST_DATA_OUT}/#{subpath}.tmp", "#{TEST_DATA_OUT}/#{subpath}"
      end
    else
      FileUtils.mkdir_p "#{TEST_DATA_OUT}/#{File.dirname(subpath)}"
      FileUtils.cp path, "#{TEST_DATA_OUT}/#{subpath}"
    end
  end
end


desc "Run all examples"
#task 'spec'=>[ 'test:data:prepare' ] do
task 'spec', :key do |t, args|
  jar_dir = File.dirname(__FILE__) + '/target/dependencies'
  jars = Dir[ "#{jar_dir}/*.jar" ]

  args.with_defaults( :key=>'*' )
  spec_files = FileList["specs/**/#{args[:key]}_spec.rb"]

  puts "running #{spec_files}"
  cmd = "jruby -J-classpath #{jars.join(':')} -S spec #{spec_files}" 
  puts cmd
  run3( cmd )
end


version = ENV['project.version'] || ENV['VERSION'] || '1.0.0'

if ( version =~ /^([0-9]+)\.([0-9]+)\.([0-9]+)(\..*)?/ )
  PROJECT_VERSION="#{$1}.#{$2}.#{$3}"
end

task 'maven:package'=>[ :package ]

spec = eval( File.read( "src/main/assembly/vfs.gemspec" ) )

Rake::GemPackageTask.new(spec) do |pkg|
    pkg.package_dir = 'target/gems'
end

task 'novfs' do
  ENV['NOVFS']='true'
end

task 'rubyspec' => [ 'rubyspec:checkout' ] do
  fq_specs = SPECS.collect{|e| "#{RUBYSPEC_DIR}/#{e}"}
  classpath = Dir[ "#{DEP_JARS_DIR}/*.jar" ].join(':')

  cmd = [ 'jruby' ]

  unless ( ENV['NOVFS'] )
    cmd << "-J-classpath #{classpath}"
  end

  cmd << '-S mspec'
  cmd << "-B #{RUBYSPEC_DIR}/ruby.1.8.mspec" 

  unless( ENV['NOVFS'] )
    cmd << "-T-I#{File.dirname(__FILE__)}/lib"
    cmd << '-T-rvfs' 
  end
  
  cmd << '--format html'
  cmd << "--output #{File.dirname(__FILE__)}/target/rubyspec#{ ENV['NOVFS'] ? '-novfs' : '' }.html"
  cmd << fq_specs 
  cmd.flatten!
  run3( cmd.join(' ') )
end

file RUBYSPEC_DIR do
  cmd = "git clone git://github.com/torquebox/rubyspec.git #{RUBYSPEC_DIR}"
  run3(cmd)
end

task 'rubyspec:checkout'=>[ RUBYSPEC_DIR]
  

def run3(cmd)
  puts "Running:\n  #{cmd}"
  r = Open3.popen3( cmd ) do |stdin, stdout, stderr|
    stdin.close
    stdout_thr = Thread.new(stdout) {|stdout_io|
      while ( ! ( c = stdout_io.getc ).nil? )
        putc c
      end
      stdout_io.close
    }
    stderr_thr = Thread.new(stderr) {|stderr_io|
      while ( ! ( c = stderr_io.getc ).nil? )
        putc c
      end
      stderr_io.close
    }
    stdout_thr.join
    stderr_thr.join
  end
end
