
require 'open3'
require 'rake/gempackagetask'


TEST_DATA_IN  = File.dirname(__FILE__) + '/test-data'
TEST_DATA_OUT = File.dirname(__FILE__) + '/target/test-data'

desc "Prepare test-data"
task 'test:data:prepare' do
  puts "preparing test-data"

  FileUtils.rm_rf( TEST_DATA_OUT )
  FileUtils.mkdir_p( TEST_DATA_OUT )

  paths = Dir[ TEST_DATA_IN + '/**/*' ]
  paths.sort!{|l,r| r.length <=> l.length}
  #paths = paths.collect{|e| e[ TEST_DATA_IN.length..-1] }

  paths.each do |path|
    subpath = path[ TEST_DATA_IN.length..-1 ]
    if ( File.directory?( path ) )
      if ( path =~ /\.jar$/ )
        puts "replace dir with real jar for #{subpath}"
        Dir.chdir( "#{TEST_DATA_OUT}/#{subpath}" ) do 
          cmd = "jar cvf #{TEST_DATA_OUT}/#{subpath}.tmp ."
          puts cmd
          `#{cmd}`
        end
        FileUtils.rm_rf "#{TEST_DATA_OUT}/#{subpath}"
        FileUtils.mv "#{TEST_DATA_OUT}/#{subpath}.tmp", "#{TEST_DATA_OUT}/#{subpath}"
      end
    else
      FileUtils.mkdir_p "#{TEST_DATA_OUT}/#{File.dirname(subpath)}"
      FileUtils.cp path, "#{TEST_DATA_OUT}/#{subpath}"
    end
  end
end


desc "Run all examples"
#task 'spec'=>[ 'test:data:prepare' ] do
task 'spec', :key do |t, args|
  jar_dir = File.dirname(__FILE__) + '/target/dependencies'
  jars = Dir[ "#{jar_dir}/*.jar" ]

  args.with_defaults( :key=>'*' )
  spec_files = FileList["specs/**/#{args[:key]}_spec.rb"]

  puts "running #{spec_files}"
  cmd = "jruby -J-classpath #{jars.join(':')} -S spec #{spec_files}" 
  puts cmd
  r = Open3.popen3( cmd ) do |stdin, stdout, stderr|
    stdin.close
    stdout_thr = Thread.new(stdout) {|stdout_io|
      stdout_io.readlines.each do |l|
        puts l
      end
      stdout_io.close
    }
    stderr_thr = Thread.new(stderr) {|stderr_io|
      stderr_io.readlines.each do |l|
        puts l
      end
    }
    stdout_thr.join
    stderr_thr.join
  end
end


version = ENV['project.version'] || ENV['VERSION'] || '1.0.0'

if ( version =~ /^([0-9]+)\.([0-9]+)\.([0-9]+)(\..*)?/ )
  PROJECT_VERSION="#{$1}.#{$2}.#{$3}"
end

task 'maven:package'=>[ :package ]

spec = eval( File.read( "src/main/assembly/vfs.gemspec" ) )

Rake::GemPackageTask.new(spec) do |pkg|
    pkg.package_dir = 'target/gems'
end
