source 'http://rubygems.org'

gem 'rails', '~>3.1'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem "activerecord-jdbc-adapter", '~> 1.2.0', :require => "arjdbc"
gem "jdbc-h2"
gem "jdbc-sqlite3"

gem 'jruby-openssl'
gem 'json'

# Gems used only for assets and not required
# in production environments by default.

#group :assets do
  puts "loading the assets group for some stupid reason"
  #gem 'sass-rails',  "3.1.0"
  #gem 'coffee-rails', "3.1.0"
  #gem 'railties', '3.1.0'
  #gem 'uglifier'
#end

gem 'jquery-rails'
gem 'therubyrhino'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

gem "torquebox-rake-support"
gem "torquebox"
