source "file://#{File.dirname(__FILE__)}/../../../../assemblage/assembly/target/stage/gem-repo"
source 'http://rubygems.org'

gem 'rails', '3.2.2'
gem 'activerecord-jdbc-adapter'
gem 'jdbc-sqlite3'
gem 'jruby-openssl'

gem 'torquebox'
