source "file://#{File.dirname(__FILE__)}/../../../../build/assembly/target/stage/gem-repo"

gem 'rails', '3.2.7'
gem 'activerecord-jdbc-adapter'
gem 'jdbc-sqlite3'
gem 'jruby-openssl'

gem 'torquebox'
