
task :default do
  puts "copying #{ASSEMBLY_DIR} to #{BUILD_DIR}/integ-dist as hard links"
  begin
    IO.popen( "sh setup.sh #{ASSEMBLY_DIR} #{BUILD_DIR}/integ-dist #{ROOT_WAR}", 'r' ) do |io|
      while ( ! ( s = io.gets ).nil? )
        puts "cp: #{s}"
      end
    end
  rescue => e
    puts e.backtrace
  end
end
