source 'http://rubygems.org'

gem 'haml'

group :provided do
  gem 'rails', '3.0.3'
  gem 'activerecord-jdbc-adapter'
  gem 'jdbc-sqlite3'
end
  
group :development do
  gem "torquebox-rake-support", '~>1.0.0'
end

