source 'http://rubygems.org'

gem 'rails', '3.0.3'

platforms :jruby do
  gem "activerecord-jdbc-adapter", "0.9.7", :require => "jdbc_adapter"
  gem "jdbc-sqlite3"
  gem "jruby-openssl"
end

group :development do
  gem "torquebox-rake-support"
end
